name: 🍧 Auto Generate .env

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧐 Check if .env exists
        id: check_env
        run: |
          if [ -f ".env" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: 🍩 Generate default .env
        if: steps.check_env.outputs.exists == 'false'
        run: |
          cat > .env << 'EOF'
          # ===== DEVELOPER MODE =====
          IS_IZUMI=false

          # ===== STAFF =====
          NEWSLETTER=YOUR_NEWSLETTER_ID
          GROUP=YOUR_GROUP_LINK
          WEBSITE=YOUR_WEBSITE_URL

          # ===== PAIRING =====
          PAIRING_NUMBER=1234567890
          PAIRING_AUTH=true

          # ===== API =====
          API_BTZ=https://api.example.com
          APIKEY_BTZ=yourapikey

          # ===== VPS PANEL =====
          PANEL_DOMAIN=https://
          PANEL_APIKEY=ptla_yourkey
          PANEL_CAPIKEY=ptlc_yourkey
          PANEL_NESTID=1
          PANEL_EGG=1
          PANEL_LOC=1

          VPS_HOST=127.0.0.1
          VPS_PORT=22
          VPS_USERNAME=root
          VPS_PASSWORD=password

          DIGITALOCEAN_TOKEN=yourtoken

          # ===== GITHUB =====
          PAT_TOKEN=yourtoken

          # ===== CLOUDFLARE =====
          CF_ZONE=yourzone
          CF_APIKEY=yourapikey
          EOF

      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: 🧁 Commit & Push default .env
        if: steps.check_env.outputs.exists == 'false'
        run: |
          git config user.name "Liora Bot"
          git config user.email "bot@liora.local"
          git add -f .env
          git commit -m "🍬 Auto-generate default .env" || echo "🍩 No changes"
          git push origin main