name: 🍡 Sync README to Profile 🍩

on:
  push:
    branches:
      - main
    paths:
      - README.md

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 🍙 Checkout Liora repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🍩 Clone Profile Repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/naruyaizumi/naruyaizumi.git profile-repo

      - name: 🍰 Copy README.md (or fallback if missing)
        run: |
          if [ -f README.md ]; then
            echo "📥 Found README.md in liora, syncing..."
            cp README.md profile-repo/README.md
          else
            echo "⚠️ No README.md found in liora, keeping existing profile README"
          fi

      - name: 🍬 Commit & Push to Profile Repo
        run: |
          cd profile-repo
          git config user.name "🍡 Liora Bot"
          git config user.email "bot@liora.local"
          git add README.md || true
          git commit -m "🍰 Sync README from Liora Repo" || echo "✨ No changes to commit"
          git push origin main
